[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --tb=short
    --html=reports/report.html
    --self-contained-html
    --junitxml=reports/junit.xml
    --alluredir=allure-results

markers =
    e2e: end-to-end full flow tests
    smoke: kısa smoke testleri
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
